# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
env_files:
  github_token: ~/.tokens/github_ldget
brew:
  github:
    owner: ontola
    name: ldget
  commit_author:
    name: Joep Meindertsma
    email: joep@ontola.io
  folder: Formula
  homepage: "https://github.com/ontola/ldget"
  description: "A simple command line interface tool to get RDF items using HTTP GET requests."
