name: ldt
version: git
# Max 79 chars
summary: Linked Data Tool
description: |
  LDF is a CLI for gettings and manipulating RDF data

grade: devel
confinement: devmode

parts:
  ldt:
    source: .
    plugin: go
    go-importpath: /github.com/ontola/ldt

apps:
  ldt:
    command: ldt
