name: ldget
version: git
# Max 79 chars
summary: Linked Data Get
description: |
  ldget is a CLI for getting RDF data

grade: devel
confinement: devmode

parts:
  ldget:
    source: .
    plugin: go
    go-importpath: /github.com/ontola/ldget

apps:
  ldget:
    command: ldget
